CREATE TABLE SCRUM_TEAM
(
    EMP_ID     INTEGER PRIMARY KEY,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME  VARCHAR(30) NOT NULL,
    JOB_TITLE  VARCHAR(20)
);

INSERT INTO SCRUM_TEAM(EMP_ID, FIRST_NAME, LAST_NAME, JOB_TITLE)
VALUES (001, 'BURAK', 'ARIKBOĞA', 'QA ENGINEER');

INSERT INTO SCRUM_TEAM
VALUES (2, 'AHMET', 'AÇIK', 'QA/SDET');
INSERT INTO SCRUM_TEAM
VALUES (3, 'SERPİL', 'ÖZÜLÜ', 'PO');
INSERT INTO SCRUM_TEAM
VALUES (4, 'ECE', 'ACAR', 'BA');
INSERT INTO SCRUM_TEAM
VALUES (5, 'LUNA', 'OLIVENDER', 'PO');

/*
 DELETE ROW FROM TABLE

 DELETE FROM SCRUM_TEAM
 WHERE EMP_ID = 3;
 */

UPDATE SCRUM_TEAM
SET FIRST_NAME = 'ECE NUR'
WHERE EMP_ID = 4;

UPDATE SCRUM_TEAM
SET JOB_TITLE = 'PM'
WHERE EMP_ID = 5;

UPDATE SCRUM_TEAM
SET LAST_NAME='OLLIVANDER'
WHERE JOB_TITLE = 'PM';

ALTER TABLE SCRUM_TEAM
    ADD SALARY INTEGER;

UPDATE SCRUM_TEAM
SET SALARY = 3000
WHERE SALARY IS NULL;

UPDATE SCRUM_TEAM
SET SALARY = 130000
WHERE JOB_TITLE = 'SM';

UPDATE SCRUM_TEAM
SET JOB_TITLE = 'QA/SDET'
WHERE JOB_TITLE != 'PM';

UPDATE SCRUM_TEAM
SET JOB_TITLE = 'SM'
WHERE FIRST_NAME = 'LUNA';

INSERT INTO SCRUM_TEAM
VALUES (6, 'BLUE', 'OCEAN', 'PO', 17000);

UPDATE SCRUM_TEAM
SET SALARY = 170000
WHERE SALARY = 17000;

UPDATE SCRUM_TEAM
SET SALARY = 160000
WHERE EMP_ID = 1;

-- RENAME THE COLUMN
ALTER TABLE SCRUM_TEAM RENAME COLUMN SALARY TO ANNUAL_SALARY;

/* DELETE THE COLUMN

ALTER TABLE SCRUM_TEAM DROP COLUMN ANNUAL_SALARY;

*/

ALTER TABLE SCRUM_TEAM RENAME TO AGILE_TEAM;


-- *********************************************************************************
-- WE USE TRUNCATE IF WE WANT TO DELETE ALL THE DATA FROM THE TABLE
-- BUT STILL KEEP THE TABLE STRUCTURE
-- SYNTAX: (DON'T RUN IT TO KEEP TABLE FOR UPCOMING QUERY PRACTICES)
-- TRUNCATE TABLE AGILE_TEAM;


-- *********************************************************************************
-- WE USE DROP IF WE WANT TO DELETE TABLE AND IT'S ALL DATA
-- SYNTAX: (DON'T RUN IT TO KEEP TABLE FOR UPCOMING QUERY PRACTICES)
-- DROP TABLE AGILE_TEAM;


SELECT *
FROM AGILE_TEAM
ORDER BY EMP_ID;
