-- GET ME ALL EMPLOYEES FIRST_NAME, LAST_NAME AND THEIR MANAGER'S FIRST_NAME AND LAST_NAME
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, MANAGER.EMPLOYEE_ID, MANAGER.FIRST_NAME, MANAGER.LAST_NAME
FROM EMPLOYEES E
         LEFT JOIN EMPLOYEES MANAGER ON E.MANAGER_ID = MANAGER.EMPLOYEE_ID
ORDER BY E.EMPLOYEE_ID;

