SELECT FIRST_NAME, LAST_NAME, ADDRESS, PHONE
FROM CUSTOMER C
         JOIN ADDRESS A ON A.ADDRESS_ID = C.ADDRESS_ID;

SELECT FIRST_NAME, LAST_NAME, C.ADDRESS_ID, ADDRESS, PHONE
FROM CUSTOMER C
         LEFT JOIN ADDRESS A ON A.ADDRESS_ID = C.ADDRESS_ID;

SELECT FIRST_NAME, LAST_NAME, A.ADDRESS_ID, ADDRESS, PHONE
FROM CUSTOMER C
         RIGHT JOIN ADDRESS A ON A.ADDRESS_ID = C.ADDRESS_ID;

SELECT FIRST_NAME, LAST_NAME, A.ADDRESS_ID, C.ADDRESS_ID, ADDRESS, PHONE
FROM CUSTOMER C
         FULL JOIN ADDRESS A ON A.ADDRESS_ID = C.ADDRESS_ID;


-- I WANT TO SEE FIRST_NAME, LAST_NAME AND DEPARTMENT_NAME OF THE EMPLOYEES
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES
         LEFT JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

INSERT INTO CUSTOMER
VALUES (6, 'BURAK', 'ARIKBOĞA', 5);

UPDATE CUSTOMER
SET ADDRESS_ID = NULL
WHERE FIRST_NAME = 'BURAK';

SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, C.ADDRESS_ID, A.ADDRESS_ID, PHONE
FROM CUSTOMER C
         LEFT OUTER JOIN ADDRESS A ON C.ADDRESS_ID = A.ADDRESS_ID
WHERE A.ADDRESS_ID IS NULL;

COMMIT;

SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, C.ADDRESS_ID, A.ADDRESS_ID, ADDRESS, PHONE
FROM CUSTOMER C
         FULL OUTER JOIN ADDRESS A ON C.ADDRESS_ID = A.ADDRESS_ID
WHERE A.ADDRESS_ID IS NULL
   OR C.ADDRESS_ID IS NULL;

-- GET ME ALL INFO OF WHO DON'T HAVE DEPARTMENT NAME
SELECT *
FROM EMPLOYEES E
         LEFT JOIN DEPARTMENTS D on E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_NAME IS NULL;

-- GET ME FIRST_NAME, LAST_NAME, DEPARTMENT_NAME, CITY, COUNTRY_NAME AND REGION_NAME FOR ALL EMPLOYEES
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME, CITY, COUNTRY_NAME, REGION_NAME
FROM EMPLOYEES E
         LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
         LEFT JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
         LEFT JOIN COUNTRIES C2 on C2.COUNTRY_ID = L.COUNTRY_ID
         LEFT JOIN REGIONS R on C2.REGION_ID = R.REGION_ID;