--WHO IS MAKING HIGHEST SALARY
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY)
                FROM EMPLOYEES);

-- WHO IS MAKING SECOND HIGHEST SALARY
SELECT *
FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY)
                FROM EMPLOYEES
                WHERE SALARY < (SELECT MAX(SALARY)
                                FROM EMPLOYEES));

-- GET ME THE TOP TEN SALARY EMPLOYEES
SELECT *
FROM EMPLOYEES
WHERE SALARY >= (SELECT MIN(SALARY)
                 FROM (SELECT DISTINCT SALARY
                       FROM EMPLOYEES
                       ORDER BY SALARY DESC)
                 WHERE ROWNUM < 11)
ORDER BY SALARY DESC;


-- GET ME THE SALARY AND COUNT OF SALARY OF TOP TEN SALARY EMPLOYEES
SELECT SALARY, COUNT(SALARY)
FROM EMPLOYEES
WHERE SALARY >= (SELECT MIN(SALARY)
                 FROM (SELECT DISTINCT SALARY
                       FROM EMPLOYEES
                       ORDER BY SALARY DESC)
                 WHERE ROWNUM < 11)
GROUP BY SALARY
ORDER BY SALARY DESC;


-- FIND EMPLOYEE INFO WHO IS MAKING 14TH HIGHEST SALARY
SELECT *
FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY)
                FROM (SELECT SALARY
                      FROM (SELECT DISTINCT SALARY
                            FROM EMPLOYEES
                            ORDER BY SALARY DESC)
                      WHERE ROWNUM < 15));